<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHxJRY6x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHxJRY6x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHxJRY6x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHxJRY6x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHxJRY6x\App_KernelDevDebugContainer([
    'container.build_hash' => 'HxJRY6x',
    'container.build_id' => '92ba1ab2',
    'container.build_time' => 1634116098,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHxJRY6x');
